In [246]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from dataset import *

In [247]:
df = pd.read_csv( "../ML-Project-CS361/cleaned_shifted_data.csv" ) 
drop_cols = [0,1,2,12,14,16]
drop_cols = df.columns[drop_cols]
drop_cols

Index(['Timestamp', 'Unnamed: 0', 'Station', 'Checks', 'AQI_bucket_calculated',
       'AQI_bucket_calculated_shifted'],
      dtype='object')

In [248]:
df.shape

(174762, 17)

In [249]:
df.drop(columns=drop_cols, inplace=True)

In [250]:
df.corr()['AQI_calculated_shifted']

PM2.5 (µg/m³)             0.502895
PM10 (µg/m³)              0.412791
NO (µg/m³)                0.281539
NO2 (µg/m³)               0.171903
NOx (ppb)                 0.245873
NH3 (µg/m³)               0.202202
SO2 (µg/m³)              -0.081608
CO (mg/m³)                0.391340
Ozone (µg/m³)            -0.013711
AQI_calculated            0.604224
AQI_calculated_shifted    1.000000
Name: AQI_calculated_shifted, dtype: float64

In [251]:
column_types = df.dtypes
print(column_types)

PM2.5 (µg/m³)             float64
PM10 (µg/m³)              float64
NO (µg/m³)                float64
NO2 (µg/m³)               float64
NOx (ppb)                 float64
NH3 (µg/m³)               float64
SO2 (µg/m³)               float64
CO (mg/m³)                float64
Ozone (µg/m³)             float64
AQI_calculated            float64
AQI_calculated_shifted    float64
dtype: object

In [252]:
df_np=df.to_numpy()
df_np.shape

(174762, 11)

In [253]:
X = df.drop(columns=[ 'AQI_calculated_shifted'])
X.columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)',
       'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'AQI_calculated'],
      dtype='object')

In [254]:
Y=df['AQI_calculated_shifted']
Y

0         296.0
1         297.0
2         298.0
3         298.0
4         299.0
          ...
174757    219.0
174758    219.0
174759    219.0
174760    220.0
174761    220.0
Name: AQI_calculated_shifted, Length: 174762, dtype: float64

In [200]:
X,Y = load_dataset()
X.shape

(174762, 14)

In [255]:
Y.shape

(174762,)

In [256]:
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size =0.3,  random_state = 0 )

In [257]:

X_train_np=X_train.to_numpy()
Y_train_np=Y_train.to_numpy()

In [258]:
X_train

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),AQI_calculated
49172,24.00,163.00,0.21,10.27,5.10,2.41,19.96,0.46,29.00,122.0
50053,89.00,195.00,54.00,17.77,48.98,6.73,21.68,1.97,13.56,193.0
139770,31.00,80.00,2.07,3.55,5.72,7.36,18.96,0.58,15.70,261.0
149023,229.40,304.10,28.67,9.59,35.64,21.23,5.61,0.71,2.69,267.0
5361,59.00,83.00,56.97,16.26,111.13,10.64,17.77,0.66,13.98,93.0
...,...,...,...,...,...,...,...,...,...,...
95939,21.00,72.00,5.21,2.67,5.16,4.76,11.08,0.23,9.59,177.0
152315,35.00,206.30,0.25,2.22,1.69,20.78,4.67,0.17,14.64,89.0
117952,12.00,30.86,1.24,2.08,3.47,3.56,28.23,0.37,16.32,47.0
173685,9.00,26.00,6.50,3.80,7.30,5.10,7.70,2.34,2.60,115.0
43567,18.25,52.50,5.51,12.35,10.00,0.96,18.95,0.55,16.93,38.0

In [259]:
Y_train_np.shape

(122333,)

In [260]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression().fit(X_train_np, Y_train_np)
Y_pred_train = lr.predict(X_train_np)
Y_pred_train

array([102.75298379, 204.66194705, 194.33357145, ...,  77.26173936,
       137.19331854,  80.3738818 ])

In [261]:

import numpy as np
from numpy.linalg import inv

class Linear_Regression:
    def __init__(self):
        pass
# Generally: y[i] = alpha + (beta_1 * x_1[i]) + (beta_2 * x_2[i]) + (beta_3 * x_3[i]) + error
# Model:     y_hat[i] = alpha_hat + (beta_1_hat * x_1[i]) + (beta_2_hat * x_2[i]) + (beta_3_hat * x_3[i])

    def predict(self, model, X):
        '''
        Obtain the predictions for the given model and inputs.

        model: np.array of Floats with shape (p,) of parameters
        X: np.array of Floats with shape (n, p-1) of inputs

        Returns: np.array of Floats with shape (n,).
        '''
        (n, p_minus_one) = X.shape
        p = p_minus_one + 1

        new_X = np.ones(shape=(n, p))
        new_X[:, 1:] = X

        return np.dot(new_X, model)
    
    def fit(self, X, y):
        '''
        Returns the model with the parameters that minimize the MSE.

        X: np.array of Floats with shape (n, p-1) of inputs
        y: np.array of Floats with shape (n,) of observed outputs

        Returns: np.array of shape (p,) representing the model.
        '''
        (n, p_minus_one) = X.shape
        p = p_minus_one + 1

        new_X = np.ones(shape=(n, p))
        new_X[:, 1:] = X

        return np.dot(np.dot(inv(np.dot(new_X.T, new_X)), new_X.T), y)

In [262]:
X

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),AQI_calculated
0,46.00,80.00,1.29,9.16,12.02,27.19,13.56,0.40,15.80,67.0
1,46.00,80.00,1.74,8.93,12.48,30.29,13.71,0.41,15.52,68.0
2,45.62,79.92,1.87,8.56,12.17,28.20,13.88,0.41,15.33,68.0
3,41.00,72.92,1.83,8.72,12.37,26.69,13.77,0.40,15.30,68.0
4,41.00,79.00,1.69,7.91,11.30,26.83,13.87,0.41,15.49,68.0
...,...,...,...,...,...,...,...,...,...,...
174757,72.00,116.00,6.40,3.30,6.90,4.90,44.20,0.63,68.00,252.0
174758,71.00,114.00,6.40,3.40,7.00,4.90,41.30,0.68,69.10,249.0
174759,71.00,114.00,6.30,3.50,7.00,4.90,42.20,0.73,66.90,247.0
174760,73.00,114.00,6.30,5.00,7.80,5.50,0.40,0.76,44.60,238.0
174761,70.00,230.00,6.30,5.70,8.20,5.70,0.20,0.79,36.50,227.0

In [263]:
predictions_df_train = pd.DataFrame({
                               
                               'PM2.5 (µg/m³)': X_train['PM2.5 (µg/m³)'],
                               'PM10 (µg/m³)': X_train['PM10 (µg/m³)'],
                               'NO (µg/m³)': X_train['NO (µg/m³)'],
                               'NO2 (µg/m³)': X_train['NO2 (µg/m³)'],
                               'NOx (ppb)': X_train['NOx (ppb)'],
                               'NH3 (µg/m³)': X_train['NH3 (µg/m³)'],
                               'SO2 (µg/m³)': X_train['SO2 (µg/m³)'],
                               'CO (mg/m³)': X_train['CO (mg/m³)'],
                               'AQI_calculated': X_train['AQI_calculated'],
                               'AQI_calculated_shifted': Y_train,
    'Sklearn AQI Predictions':Y_pred_train
                               })
predictions_df_train

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),AQI_calculated,AQI_calculated_shifted,Sklearn AQI Predictions
49172,24.00,163.00,0.21,10.27,5.10,2.41,19.96,0.46,122.0,192.0,102.752984
50053,89.00,195.00,54.00,17.77,48.98,6.73,21.68,1.97,193.0,156.0,204.661947
139770,31.00,80.00,2.07,3.55,5.72,7.36,18.96,0.58,261.0,324.0,194.333571
149023,229.40,304.10,28.67,9.59,35.64,21.23,5.61,0.71,267.0,332.0,260.784247
5361,59.00,83.00,56.97,16.26,111.13,10.64,17.77,0.66,93.0,79.0,127.521466
...,...,...,...,...,...,...,...,...,...,...,...
95939,21.00,72.00,5.21,2.67,5.16,4.76,11.08,0.23,177.0,134.0,154.503920
152315,35.00,206.30,0.25,2.22,1.69,20.78,4.67,0.17,89.0,306.0,85.504183
117952,12.00,30.86,1.24,2.08,3.47,3.56,28.23,0.37,47.0,73.0,77.261739
173685,9.00,26.00,6.50,3.80,7.30,5.10,7.70,2.34,115.0,116.0,137.193319
43567,18.25,52.50,5.51,12.35,10.00,0.96,18.95,0.55,38.0,35.0,80.373882

In [264]:
linear_regression = Linear_Regression()

In [265]:
model = linear_regression.fit(X_train_np, Y_train_np)
predictions_df_train['Our Predictions'] = linear_regression.predict(model, X_train_np)
predictions_df_train

AttributeError: 'Linear_Regression' object has no attribute 'fit'

In [238]:
X_test_np=X_test.to_numpy()
Y_test_np=Y_test.to_numpy()

In [239]:
X_test_np, Y_test_np

(array([[233.11, 428.11,  82.72, ...,   0.  ,   0.  ,   1.  ],
        [ 82.  , 113.  ,  11.56, ...,   0.  ,   1.  ,   0.  ],
        [115.  , 260.62,   5.49, ...,   0.  ,   0.  ,   1.  ],
        ...,
        [ 28.  ,  56.  ,   5.38, ...,   0.  ,   0.  ,   1.  ],
        [ 21.  ,  27.  ,   5.4 , ...,   0.  ,   0.  ,   1.  ],
        [ 32.  ,  59.  ,   1.01, ...,   0.  ,   1.  ,   0.  ]]),
 array([325., 149., 301., ..., 227., 132.,  32.]))

In [240]:
lr_test=LinearRegression().fit(X_test_np, Y_test_np)
Y_pred_test = lr.predict(X_test_np)
Y_pred_test

array([306.62641468, 144.44254031, 184.63640196, ..., 111.96034329,
       100.0718627 , 100.60588084])

In [241]:
predictions_df_test = pd.DataFrame({
                               
                               'PM2.5 (µg/m³)': X_test['PM2.5 (µg/m³)'],
                               'PM10 (µg/m³)': X_test['PM10 (µg/m³)'],
                               'NO (µg/m³)': X_test['NO (µg/m³)'],
                               'NO2 (µg/m³)': X_test['NO2 (µg/m³)'],
                               'NOx (ppb)': X_test['NOx (ppb)'],
                               'NH3 (µg/m³)': X_test['NH3 (µg/m³)'],
                               'SO2 (µg/m³)': X_test['SO2 (µg/m³)'],
                               'CO (mg/m³)': X_test['CO (mg/m³)'],
                               'AQI_calculated': X_test['AQI_calculated'],
                               'AQI_calculated_shifted': Y_test,
    'Sklearn AQI Predictions':Y_pred_test
                               })
predictions_df_test

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),AQI_calculated,AQI_calculated_shifted,Sklearn AQI Predictions
51427,233.11,428.11,82.72,14.19,68.66,4.17,23.71,3.68,321.0,325.0,306.626415
83982,82.00,113.00,11.56,2.93,17.70,11.87,19.27,0.82,121.0,149.0,144.442540
88698,115.00,260.62,5.49,2.57,5.34,11.81,10.26,1.03,203.0,301.0,184.636402
51363,123.00,221.00,14.03,14.72,17.64,5.03,22.09,1.51,324.0,326.0,246.461898
102949,81.00,121.00,5.30,2.85,5.36,6.17,12.50,1.35,107.0,180.0,136.051782
...,...,...,...,...,...,...,...,...,...,...,...
135147,18.57,62.43,5.38,1.91,5.03,4.79,9.23,0.29,127.0,47.0,112.756753
140757,31.00,83.00,1.41,0.67,2.46,9.38,20.52,0.46,181.0,267.0,150.719313
95688,28.00,56.00,5.38,2.62,5.30,5.44,12.12,0.30,150.0,227.0,111.960343
136279,21.00,27.00,5.40,2.31,5.23,4.60,8.65,0.31,40.0,132.0,100.071863
115255,32.00,59.00,1.01,1.38,2.53,5.14,14.63,0.49,76.0,32.0,100.605881

In [242]:
model = linear_regression.fit(X_test_np, Y_test_np)
predictions_df_test['Our Predictions'] = linear_regression.predict(model, X_test_np)
predictions_df_test

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),AQI_calculated,AQI_calculated_shifted,Sklearn AQI Predictions,Our Predictions
51427,233.11,428.11,82.72,14.19,68.66,4.17,23.71,3.68,321.0,325.0,306.626415,272.819347
83982,82.00,113.00,11.56,2.93,17.70,11.87,19.27,0.82,121.0,149.0,144.442540,152.871222
88698,115.00,260.62,5.49,2.57,5.34,11.81,10.26,1.03,203.0,301.0,184.636402,148.795518
51363,123.00,221.00,14.03,14.72,17.64,5.03,22.09,1.51,324.0,326.0,246.461898,213.180217
102949,81.00,121.00,5.30,2.85,5.36,6.17,12.50,1.35,107.0,180.0,136.051782,99.258451
...,...,...,...,...,...,...,...,...,...,...,...,...
135147,18.57,62.43,5.38,1.91,5.03,4.79,9.23,0.29,127.0,47.0,112.756753,77.680490
140757,31.00,83.00,1.41,0.67,2.46,9.38,20.52,0.46,181.0,267.0,150.719313,160.580390
95688,28.00,56.00,5.38,2.62,5.30,5.44,12.12,0.30,150.0,227.0,111.960343,77.340851
136279,21.00,27.00,5.40,2.31,5.23,4.60,8.65,0.31,40.0,132.0,100.071863,63.204306
115255,32.00,59.00,1.01,1.38,2.53,5.14,14.63,0.49,76.0,32.0,100.605881,109.289156

In [243]:
mean_squared_error(Y_test,predictions_df_test['Our Predictions'])

8101.149700993494

In [244]:
mean_squared_error(Y_test,predictions_df_test['Sklearn AQI Predictions'])

6556.978086448505